// D7 export tests: the `Get Code` dialog (Dart / JSON / CLI), the copy
// buttons with the 2 s copied state, and `Open Preset` validation.
//
// The Dart tab is asserted against the kit generator's own output — the
// generated per-preset `dart` source in `docs_preset_sources.dart` — which is
// what `flutter_shadcn theme apply <id>` writes into a project.

import 'package:docs/generated/docs_preset_sources.dart';
import 'package:docs/routing/docs_router.dart';
import 'package:docs/state/docs_state.dart';
import 'package:docs/theme/theme_dart_source.dart';
import 'package:docs/theme/theme_document.dart';
import 'package:docs/theme/theme_export.dart';
import 'package:docs/ui/shadcn/components/button/button.dart';
import 'package:docs/ui/shadcn/components/text_area/text_area.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

import 'support/app_harness.dart';

void main() {
  group('payload builders', () {
    test('the Dart payload of an untouched preset is the generator output', () {
      final DocsState state = DocsState(storage: MemoryDocsStorage());
      addTearDown(state.dispose);
      expect(state.themeModel.dartSource, kPresetSources['neutral']!.dart);
      expect(
        state.themeModel.dartSource,
        startsWith(
          '// Generated by flutter_shadcn — regenerate with: '
          'flutter_shadcn theme apply neutral --refresh',
        ),
      );
      expect(state.themeModel.dartSource, contains('import \'theme.dart\';'));
    });

    test('the Dart payload follows every rail edit', () {
      final DocsState state = DocsState(storage: MemoryDocsStorage());
      addTearDown(state.dispose);
      state.themeModel
        ..selectPreset('claude')
        ..setRadiusPx(0)
        ..setFont('mono', 'JetBrains Mono, monospace');
      expect(
        state.themeModel.dartSource,
        themeDartSource(state.themeModel.document),
      );
      expect(state.themeModel.dartSource, contains('radius: 0.0'));
      expect(
        state.themeModel.dartSource,
        contains("fontMono: 'JetBrains Mono, monospace'"),
      );
      // The colour maps are untouched by a radius/font edit, so they stay
      // byte-identical to the generator's own output for the preset.
      expect(
        _colourBlock(state.themeModel.dartSource),
        _colourBlock(kPresetSources['claude']!.dart),
      );
      expect(
        state.themeModel.dartSource,
        isNot(kPresetSources['claude']!.dart),
        reason: 'the edited values must actually change the file',
      );
    });

    test('the JSON payload is the canonical document and round-trips', () {
      final DocsState state = DocsState(storage: MemoryDocsStorage());
      addTearDown(state.dispose);
      expect(state.themeModel.json, kPresetSources['neutral']!.json);
      state.themeModel.setRadiusPx(16);
      expect(state.themeModel.json, isNot(kPresetSources['neutral']!.json));
      expect(
        ThemeDocument.fromJson(state.themeModel.document.toJson()).json,
        state.themeModel.json,
      );
    });

    test('the CLI tab names the preset, or explains how to register one', () {
      final DocsState state = DocsState(storage: MemoryDocsStorage());
      addTearDown(state.dispose);
      expect(
        themeCliGuide(state.themeModel.document),
        contains('flutter_shadcn theme apply neutral'),
      );
      state.themeModel.shuffle();
      expect(
        themeCliGuide(state.themeModel.document),
        contains('lib/registry/themes/shuffled.json'),
      );
      expect(themeApplyCommand('claude'), 'flutter_shadcn theme apply claude');
    });
  });

  group('Get Code dialog', () {
    testWidgets('shows three tabs and copies the active payload', (
      WidgetTester tester,
    ) async {
      final List<String> copied = <String>[];
      tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
        SystemChannels.platform,
        (MethodCall call) async {
          if (call.method == 'Clipboard.setData') {
            copied.add(
              (call.arguments as Map<Object?, Object?>)['text']! as String,
            );
          }
          return null;
        },
      );
      addTearDown(
        () => tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
          SystemChannels.platform,
          null,
        ),
      );

      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      await tester.tap(
        find.byKey(const ValueKey<String>('theme-rail-get-code')),
      );
      await tester.pumpAndSettle();

      expect(find.text('Dart'), findsOneWidget);
      expect(find.text('JSON'), findsOneWidget);
      expect(find.text('CLI'), findsOneWidget);

      // Dart first, and the copy button writes exactly that payload.
      await tester.tap(find.text('Copy'));
      await tester.pump();
      expect(copied.last, docsState.themeModel.dartSource);
      expect(copied.last, kPresetSources['neutral']!.dart);

      // Switch to JSON: the payload follows the tab.
      await tester.tap(find.text('JSON'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Copy'));
      await tester.pump();
      expect(copied.last, docsState.themeModel.json);

      await tester.tap(find.text('CLI'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Copy'));
      await tester.pump();
      expect(copied.last, contains('flutter_shadcn theme apply neutral'));
      expect(copied.length, 3);
    });

    testWidgets('the copied state resets after 2 s', (
      WidgetTester tester,
    ) async {
      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      await tester.tap(
        find.byKey(const ValueKey<String>('theme-rail-get-code')),
      );
      await tester.pumpAndSettle();
      await tester.tap(find.text('Copy'));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 1999));
      expect(
        find.byIcon(const IconData(0xe16f, fontFamily: 'MaterialIcons')),
        findsNothing,
      );
      await tester.pump(const Duration(milliseconds: 2));
      expect(find.text('Copy'), findsOneWidget);
    });
  });

  group('Open Preset dialog', () {
    testWidgets('rejects an invalid document and shows the reason', (
      WidgetTester tester,
    ) async {
      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      await tester.tap(find.text('Open Preset'));
      await tester.pumpAndSettle();

      final TextArea area = tester.widget<TextArea>(
        find.byKey(const ValueKey<String>('open-preset-input')),
      );
      area.controller!.text = '{"id":"broken","schemaVersion":1}';
      await tester.pumpAndSettle();

      await tester.tap(find.byKey(const ValueKey<String>('open-preset-apply')));
      await tester.pumpAndSettle();
      expect(find.text('preset.schemaVersion must be 2'), findsOneWidget);
      expect(docsState.presetId, 'neutral', reason: 'theme untouched');
    });

    testWidgets('applies a valid pasted document', (WidgetTester tester) async {
      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      await tester.tap(find.text('Open Preset'));
      await tester.pumpAndSettle();

      final TextArea area = tester.widget<TextArea>(
        find.byKey(const ValueKey<String>('open-preset-input')),
      );
      area.controller!.text = kPresetSources['ocean-breeze']!.json;
      await tester.pumpAndSettle();
      await tester.tap(find.byKey(const ValueKey<String>('open-preset-apply')));
      await tester.pumpAndSettle();
      expect(docsState.presetId, 'ocean-breeze');
      expect(docsState.themeModel.matchedPresetId, 'ocean-breeze');
    });

    testWidgets('the Apply button stays disabled for non-JSON input', (
      WidgetTester tester,
    ) async {
      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      await tester.tap(find.text('Open Preset'));
      await tester.pumpAndSettle();

      final TextArea area = tester.widget<TextArea>(
        find.byKey(const ValueKey<String>('open-preset-input')),
      );
      area.controller!.text = 'not json at all';
      await tester.pumpAndSettle();
      expect(
        tester
            .widget<Button>(
              find.byKey(const ValueKey<String>('open-preset-apply')),
            )
            .onPressed,
        isNull,
      );
    });
  });
}

/// The two `ShadcnColors` blocks of a generated theme file.
String _colourBlock(String source) {
  final int start = source.indexOf('const ShadcnColors');
  final int end = source.indexOf('/// Non-colour tokens');
  return source.substring(start, end);
}
