// D7: the Get Code `Dart` tab must be the file `flutter_shadcn theme apply`
// writes — byte for byte.
//
// `lib/theme/theme_dart_source.dart` is a port of the kit generator
// (`flutter_shadcn_kit/tool/rearch/gen_app_theme.dart`), which cannot run in
// the web bundle (it imports `dart:io` and lives in the kit package). The
// generated `docs_preset_sources.dart` holds the generator's real output for
// every preset, so these tests pin the port to it for all 43 presets and
// check the document round-trip that custom (shuffled) combinations rely on.

import 'dart:convert';

import 'package:docs/generated/docs_preset_sources.dart';
import 'package:docs/theme/theme_dart_source.dart';
import 'package:docs/theme/theme_document.dart';
import 'package:docs/theme/theme_document_edits.dart';
import 'package:docs/ui/shadcn/theme/color_tokens.dart';
import 'package:docs/ui/shadcn/theme/theme.dart';
import 'package:docs/ui/shadcn/theme/tokens.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('themeDartSource', () {
    test('matches the generator output for every preset', () {
      expect(kPresetSources, isNotEmpty);
      for (final DocsPresetSource source in kPresetSources.values) {
        final ThemeDocument document = ThemeDocument.fromPreset(source.id);
        expect(
          themeDartSource(document),
          source.dart,
          reason: 'app_theme.dart drifted for preset ${source.id}',
        );
      }
    });

    test('matches for an edited document too (custom combinations)', () {
      // Round-trip through the registry document, apply one real edit, and
      // re-render: the edits must not disturb the generator's shape.
      final ThemeDocument edited = ThemeDocument.fromPreset(
        'neutral',
      ).withRadiusPx(12).withFont('mono', 'JetBrains Mono, monospace');
      final String rendered = themeDartSource(edited);
      expect(rendered, contains('radius: 0.75'));
      expect(rendered, contains('spacingBase: 4.0'));
      expect(rendered, contains("fontMono: 'JetBrains Mono, monospace'"));
      expect(
        rendered,
        startsWith(
          '// Generated by flutter_shadcn — regenerate with: '
          'flutter_shadcn theme apply neutral --refresh',
        ),
      );
    });

    test('omits the font block when the document names no family', () {
      final String rendered = themeDartSource(
        ThemeDocument.fromPreset(
          'neutral',
        ).withFont('sans', null).withFont('serif', null).withFont('mono', null),
      );
      expect(rendered, isNot(contains('ShadcnFonts')));
      expect(rendered, isNot(contains('fonts:')));
    });
  });

  group('ThemeDocument', () {
    test('every registry preset round-trips to byte-identical JSON', () {
      for (final DocsPresetSource source in kPresetSources.values) {
        expect(
          ThemeDocument.fromPreset(source.id).json,
          source.json,
          reason: 'preset JSON drifted for ${source.id}',
        );
      }
    });

    test('resolves the same colours as the generated theme factory', () {
      final ThemeDocument document = ThemeDocument.fromPreset('neutral');
      final ShadcnColors light = document.colorsFor(Brightness.light);
      expect(light.background, const Color(0xFFFFFFFF));
      expect(light.foreground, const Color(0xFF0A0A0A));
      expect(light.border, const Color(0xFFE5E5E5));
      expect(light.chart1, const Color(0xFFF54900));
      // Alpha is preserved, never flattened (the shadcn dark border).
      expect(
        document.colorsFor(Brightness.dark).border,
        const Color(0x1AFFFFFF),
      );
    });

    test('scales spacing and tracking into logical pixels', () {
      final ThemeDocument document = ThemeDocument.fromPreset('neutral');
      final ShadcnTokens tokens = document.tokensFor(Brightness.light);
      expect(tokens.radius, 0.625);
      expect(tokens.spacingBase, 4);
      expect(tokens.trackingNormal, 0);
      // ShadowScale.derive recomputes the eight sizes from the six atoms.
      expect(tokens.shadows.shadow, isNotEmpty);
    });

    test('carries the document font families into the type scale', () {
      // Registry gap: no registry widget calls `Typography.applyFonts`, so
      // this is the docs-side composition that makes the font rows live.
      final ShadcnThemeData theme = ThemeDocument.fromPreset(
        'neutral',
      ).theme(Brightness.light);
      expect(theme.fonts.fontSans, 'Geist, sans-serif');
      expect(theme.fonts.fontMono, 'Geist Mono, monospace');
      expect(theme.typography.sans.fontFamily, 'Geist');
      expect(theme.typography.mono.fontFamily, 'Geist Mono');
    });

    test('rejects documents the schema forbids', () {
      Map<String, Object?> base() =>
          jsonDecode(kPresetSources['neutral']!.json) as Map<String, Object?>;

      Map<String, Object?> withoutColor() {
        final Map<String, Object?> json = base();
        (json['light']! as Map<String, Object?>).remove('primary');
        return json;
      }

      expect(
        () => ThemeDocument.fromJson(withoutColor()),
        throwsA(
          isA<ThemeDocumentException>().having(
            (ThemeDocumentException e) => e.message,
            'message',
            'preset.light.primary is required',
          ),
        ),
      );
      expect(
        () => ThemeDocument.fromJson(<String, Object?>{'id': 'x'}),
        throwsA(isA<ThemeDocumentException>()),
      );
      expect(
        () => ThemeDocument.fromJson(base()..['schemaVersion'] = 1),
        throwsA(
          isA<ThemeDocumentException>().having(
            (ThemeDocumentException e) => e.message,
            'message',
            'preset.schemaVersion must be 2',
          ),
        ),
      );
      expect(
        () => ThemeDocument.fromJson(
          base()..['light'] = <String, Object?>{'background': 'not-a-colour'},
        ),
        throwsA(isA<ThemeDocumentException>()),
      );
      expect(
        () => ThemeDocument.fromPreset('does-not-exist'),
        throwsA(isA<ThemeDocumentException>()),
      );
    });

    test('edits are total: an unknown token or colour is rejected', () {
      final ThemeDocument document = ThemeDocument.fromPreset('neutral');
      expect(
        () => document.withColor('nope', '#FFFFFF'),
        throwsA(isA<ThemeDocumentException>()),
      );
      expect(
        () => document.withColor('primary', 'blue'),
        throwsA(isA<ThemeDocumentException>()),
      );
    });
  });
}
