// D5 themes-action tests: the Copy JSON / Copy Dart / Get Code payloads.
//
// The payload builders are pure functions over the generated
// `docs_preset_sources.dart`; the widget tests drive the real rail buttons
// and capture the clipboard through the platform channel.

import 'dart:convert';

import 'package:docs/generated/docs_preset_sources.dart';
import 'package:docs/routing/docs_router.dart';
import 'package:docs/theme/theme_export.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'support/app_harness.dart';

void main() {
  group('payload builders', () {
    test('Copy JSON applies the radius slider (px / 16)', () {
      final Map<String, Object?> json =
          jsonDecode(presetJsonSource('neutral', radiusPx: 10))
              as Map<String, Object?>;
      expect(json['id'], 'neutral');
      expect(json['radius'], 0.625);
      expect((json['light']! as Map<String, Object?>).length, 32);
      expect((json['dark']! as Map<String, Object?>).length, 32);

      final Map<String, Object?> wide =
          jsonDecode(presetJsonSource('neutral', radiusPx: 16))
              as Map<String, Object?>;
      expect(wide['radius'], 1);
    });

    test('Copy JSON keeps every non-radius value untouched', () {
      final Map<String, Object?> before =
          jsonDecode(kPresetSources['claude']!.json) as Map<String, Object?>;
      final Map<String, Object?> after =
          jsonDecode(presetJsonSource('claude', radiusPx: 4))
              as Map<String, Object?>;
      expect(after['name'], before['name']);
      expect(after['light'], before['light']);
      expect(after['dark'], before['dark']);
      expect(after['fonts'], before['fonts']);
      expect(after['shadow'], before['shadow']);
    });

    test('Copy Dart is the CLI file with the CLI header and imports', () {
      final String dart = presetDartSource('neutral');
      expect(
        dart,
        startsWith(
          '// Generated by flutter_shadcn — regenerate with: '
          'flutter_shadcn theme apply neutral --refresh',
        ),
      );
      expect(dart, contains("import 'package:flutter/widgets.dart';"));
      expect(dart, contains("import 'theme.dart';"));
      expect(dart, contains("import 'color_tokens.dart';"));
      expect(dart, contains("import 'tokens.dart';"));
      expect(dart, contains('buildNeutralTheme(Brightness brightness)'));
    });

    test('Get Code is the theme apply command', () {
      expect(themeApplyCommand('claude'), 'flutter_shadcn theme apply claude');
    });
  });

  group('rail actions', () {
    testWidgets('each action writes its payload and shows Copied for 2 s', (
      WidgetTester tester,
    ) async {
      final List<String> copied = <String>[];
      tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
        SystemChannels.platform,
        (MethodCall call) async {
          if (call.method == 'Clipboard.setData') {
            copied.add(
              (call.arguments as Map<Object?, Object?>)['text']! as String,
            );
          }
          return null;
        },
      );
      addTearDown(
        () => tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
          SystemChannels.platform,
          null,
        ),
      );

      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');

      // Copy JSON — the selected preset with the effective radius applied.
      await tester.ensureVisible(find.text('Copy JSON'));
      await tester.tap(find.text('Copy JSON'));
      await tester.pump();
      expect(
        copied.single,
        presetJsonSource(
          docsState.presetId,
          radiusPx: docsState.effectiveRadiusPx,
        ),
      );
      expect(find.text('Copied'), findsOneWidget);
      await tester.pump(const Duration(milliseconds: 1999));
      expect(find.text('Copied'), findsOneWidget);
      await tester.pump(const Duration(milliseconds: 1));
      expect(find.text('Copied'), findsNothing);
      expect(find.text('Copy JSON'), findsOneWidget);

      // Copy Dart — the exact CLI `app_theme.dart` for the preset.
      await tester.tap(find.text('Copy Dart'));
      await tester.pump();
      expect(copied.last, presetDartSource(docsState.presetId));
      expect(copied.last, kPresetSources[docsState.presetId]!.dart);
      expect(find.text('Copied'), findsOneWidget);
      await tester.pump(const Duration(milliseconds: 2000));

      // Get Code — the CLI command that regenerates that file.
      await tester.tap(find.text('Get Code'));
      await tester.pump();
      expect(copied.last, 'flutter_shadcn theme apply ${docsState.presetId}');
      expect(copied.length, 3);
    });

    testWidgets('Copy JSON follows the radius slider and preset switch', (
      WidgetTester tester,
    ) async {
      final List<String> copied = <String>[];
      tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
        SystemChannels.platform,
        (MethodCall call) async {
          if (call.method == 'Clipboard.setData') {
            copied.add(
              (call.arguments as Map<Object?, Object?>)['text']! as String,
            );
          }
          return null;
        },
      );
      addTearDown(
        () => tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
          SystemChannels.platform,
          null,
        ),
      );

      final DocsRouterDelegate delegate = await pumpDocsApp(tester);
      await goTo(tester, delegate, '/themes');
      docsState.setRadiusPx(16);
      docsState.setPreset('claude');
      await tester.pump();

      await tester.ensureVisible(find.text('Copy JSON'));
      await tester.tap(find.text('Copy JSON'));
      await tester.pump();
      final Map<String, Object?> json =
          jsonDecode(copied.single) as Map<String, Object?>;
      expect(json['id'], 'claude');
      expect(json['radius'], 1);
    });
  });
}
