// GENERATED by tool/registry/gen_previews_test.dart.
//
// P6-F3 preview contract: every named example of every listed component must
// pump inside a 720x420 box and at 375 wide, under the neutral and claude
// presets in light and dark, with no exception and no overflow. Example names
// are unique per component and no preview pins its own theme.
//
// Regenerate with:
//   dart run tool/registry/gen_previews_test.dart [--check]

import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_shadcn_kit/registry/foundation/component_preview.dart';
import 'package:flutter_shadcn_kit/registry/theme/theme.dart';
import 'package:flutter_test/flutter_test.dart';

import 'themes/generated_theme.dart';

import 'package:flutter_shadcn_kit/registry/components/accordion/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/alert/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/alert_dialog/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/autocomplete/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/avatar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/badge/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/border_loading/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/breadcrumb/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/button/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/calendar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/card/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/card_image/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/carousel/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/chat/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/checkbox/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/chip/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/chip_input/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/code_snippet/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/collapsible/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/color_picker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/command/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/context_menu/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/country_flag/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/date_picker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/dialog/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/divider/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/dot_indicator/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/drawer/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/dropdown_menu/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/dropzone/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/empty_state/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/feature_carousel/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/file_diff_viewer/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/file_picker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/filter_bar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/form/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/formatted_input/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/gooey_toast/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/hover_card/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/image/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/input/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/input_otp/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/item_picker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/keyboard_shortcut/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/markdown/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/menu/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/menubar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/multi_select/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/navigation_bar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/navigation_menu/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/number_ticker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/object_input/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/overflow_marquee/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/pagination/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/phone_input/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/pinned_sheet/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/popup/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/progress/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/radio_group/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/refresh_trigger/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/resizable/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/scaffold/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/scrollbar/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/select/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/skeleton/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/slider/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/sortable/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/spinner/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/star_rating/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/stepper/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/steps/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/switch/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/table/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/tabs/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/text_animate/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/text_area/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/time_picker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/timeline/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/toast/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/toggle/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/tooltip/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/tracker/preview.dart';
import 'package:flutter_shadcn_kit/registry/components/tree/preview.dart';

/// Stage size the docs page hands an example.
const Size _stageSize = Size(720, 420);

/// Width the docs stage collapses to on a phone.
const double _phoneWidth = 375;

/// Preset directory of the registry theme layer.
String get _themesDir => '${Directory.current.path}/lib/registry/themes';

/// Presets every example is pumped under.
const List<String> _presets = <String>['neutral', 'claude'];

/// Brightnesses every example is pumped under.
const List<Brightness> _brightnesses = <Brightness>[
  Brightness.light,
  Brightness.dark,
];

/// Listed components whose `preview.dart` has not been converted yet; empty
/// on a full run.
const List<String> _pending = <String>[];

/// component id -> its named examples; the first one is the default.
final Map<String, List<ComponentPreview>> _previews =
    <String, List<ComponentPreview>>{
      'accordion': accordionPreviews,
      'alert': alertPreviews,
      'alert_dialog': alertDialogPreviews,
      'autocomplete': autocompletePreviews,
      'avatar': avatarPreviews,
      'badge': badgePreviews,
      'border_loading': borderLoadingPreviews,
      'breadcrumb': breadcrumbPreviews,
      'button': buttonPreviews,
      'calendar': calendarPreviews,
      'card': cardPreviews,
      'card_image': cardImagePreviews,
      'carousel': carouselPreviews,
      'chat': chatPreviews,
      'checkbox': checkboxPreviews,
      'chip': chipPreviews,
      'chip_input': chipInputPreviews,
      'code_snippet': codeSnippetPreviews,
      'collapsible': collapsiblePreviews,
      'color_picker': colorPickerPreviews,
      'command': commandPreviews,
      'context_menu': contextMenuPreviews,
      'country_flag': countryFlagPreviews,
      'date_picker': datePickerPreviews,
      'dialog': dialogPreviews,
      'divider': dividerPreviews,
      'dot_indicator': dotIndicatorPreviews,
      'drawer': drawerPreviews,
      'dropdown_menu': dropdownMenuPreviews,
      'dropzone': dropzonePreviews,
      'empty_state': emptyStatePreviews,
      'feature_carousel': featureCarouselPreviews,
      'file_diff_viewer': fileDiffViewerPreviews,
      'file_picker': filePickerPreviews,
      'filter_bar': filterBarPreviews,
      'form': formPreviews,
      'formatted_input': formattedInputPreviews,
      'gooey_toast': gooeyToastPreviews,
      'hover_card': hoverCardPreviews,
      'image': imagePreviews,
      'input': inputPreviews,
      'input_otp': inputOtpPreviews,
      'item_picker': itemPickerPreviews,
      'keyboard_shortcut': keyboardShortcutPreviews,
      'markdown': markdownPreviews,
      'menu': menuPreviews,
      'menubar': menubarPreviews,
      'multi_select': multiSelectPreviews,
      'navigation_bar': navigationBarPreviews,
      'navigation_menu': navigationMenuPreviews,
      'number_ticker': numberTickerPreviews,
      'object_input': objectInputPreviews,
      'overflow_marquee': overflowMarqueePreviews,
      'pagination': paginationPreviews,
      'phone_input': phoneInputPreviews,
      'pinned_sheet': pinnedSheetPreviews,
      'popup': popupPreviews,
      'progress': progressPreviews,
      'radio_group': radioGroupPreviews,
      'refresh_trigger': refreshTriggerPreviews,
      'resizable': resizablePreviews,
      'scaffold': scaffoldPreviews,
      'scrollbar': scrollbarPreviews,
      'select': selectPreviews,
      'skeleton': skeletonPreviews,
      'slider': sliderPreviews,
      'sortable': sortablePreviews,
      'spinner': spinnerPreviews,
      'star_rating': starRatingPreviews,
      'stepper': stepperPreviews,
      'steps': stepsPreviews,
      'switch': switchPreviews,
      'table': tablePreviews,
      'tabs': tabsPreviews,
      'text_animate': textAnimatePreviews,
      'text_area': textAreaPreviews,
      'time_picker': timePickerPreviews,
      'timeline': timelinePreviews,
      'toast': toastPreviews,
      'toggle': togglePreviews,
      'tooltip': tooltipPreviews,
      'tracker': trackerPreviews,
      'tree': treePreviews,
    };

/// The example inside the bounded 720x420 stage box.
Widget _stageHost(WidgetBuilder builder) {
  return SizedBox.fromSize(
    size: _stageSize,
    child: Builder(builder: builder),
  );
}

/// The same example inside a 375 wide box.
Widget _phoneHost(WidgetBuilder builder) {
  return SizedBox(
    width: _phoneWidth,
    child: Builder(builder: builder),
  );
}

/// Pumps [example] under [theme] inside [host] and asserts nothing threw or
/// overflowed.
Future<void> _pump(
  WidgetTester tester,
  ComponentPreview example,
  ShadcnThemeDataView theme,
  Widget host,
) async {
  await tester.pumpWidget(
    ShadcnTheme(
      data: ShadcnThemeData(
        colors: theme.colors,
        tokens: theme.tokens,
        fonts: theme.fonts,
      ),
      child: Directionality(
        textDirection: TextDirection.ltr,
        // The docs page runs every example inside the app shell, so an
        // Overlay exists; without it any text field in a preview throws.
        child: Overlay.wrap(child: Center(child: host)),
      ),
    ),
  );
  await tester.pump();
  // A second frame: a focus change (the command palette autofocuses its
  // search field) is delivered in the frame after the one that mounts it.
  await tester.pump(const Duration(milliseconds: 16));
  final Object? exception = tester.takeException();
  expect(
    exception,
    isNull,
    reason: 'example "${example.name}" threw: $exception',
  );
}

/// Every component that has a `preview.dart` and stays listed in the docs, read
/// from the tree so the test cannot silently lose a component when the
/// generator is not re-run.
List<String> _listedComponents(String appRoot) {
  final result = <String>[];
  for (final directory in Directory(
    '$appRoot/lib/registry/components',
  ).listSync()) {
    if (directory is! Directory) continue;
    final id = directory.path.split('/').last;
    if (!File('${directory.path}/preview.dart').existsSync()) continue;
    final meta = jsonDecode(
      File('${directory.path}/meta.json').readAsStringSync(),
    );
    if (meta is Map<String, dynamic> && meta['listed'] == false) continue;
    result.add(id);
  }
  result.sort();
  return result;
}

void main() {
  final appRoot = Directory.current.path;
  final listed = _listedComponents(appRoot);

  test('every listed component exports its examples', () {
    for (final id in listed) {
      expect(
        _previews.containsKey(id) || _pending.contains(id),
        isTrue,
        reason: 'no preview list for $id - run gen_previews_test.dart',
      );
    }
  });

  test('no building block leaks into the table', () {
    final expected = listed
        .where((String id) => !_pending.contains(id))
        .toList();
    expect(_previews.keys.toList(), expected);
  });

  test('no preview pins its own theme', () {
    for (final id in _previews.keys) {
      final file = File('$appRoot/lib/registry/components/$id/preview.dart');
      expect(file.existsSync(), isTrue, reason: '$id has no preview.dart');
      expect(
        file.readAsStringSync().contains('ShadcnThemeData('),
        isFalse,
        reason: '$id/preview.dart hard-codes a theme',
      );
    }
  });

  test('the contract class is exported from foundation', () {
    const preview = ComponentPreview('name', _placeholder);
    expect(preview.name, 'name');
    expect(preview.description, isNull);
  });

  for (final MapEntry<String, List<ComponentPreview>> entry
      in _previews.entries) {
    group(entry.key, () {
      test('exports at least one named example', () {
        expect(entry.value, isNotEmpty);
      });

      test('example names are unique', () {
        final names = entry.value
            .map((ComponentPreview example) => example.name)
            .toList();
        expect(names.toSet().length, names.length);
      });

      for (final String preset in _presets) {
        for (final Brightness brightness in _brightnesses) {
          final ShadcnThemeDataView theme = loadGeneratedTheme(
            '$_themesDir/$preset.json',
          ).view(brightness);
          testWidgets('$preset / ${brightness.name}', (
            WidgetTester tester,
          ) async {
            for (final ComponentPreview example in entry.value) {
              await _pump(tester, example, theme, _stageHost(example.builder));
              await _pump(tester, example, theme, _phoneHost(example.builder));
            }
          });
        }
      }
    });
  }
}

Widget _placeholder(BuildContext context) => const SizedBox.shrink();
