// ignore_for_file: duplicate_import, unnecessary_import, unused_import, unnecessary_null_comparison, dead_code, deprecated_member_use, use_null_aware_elements, sort_child_properties_last

import 'package:data_widget/data_widget.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart' show Divider, VerticalDivider;
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:gap/gap.dart';

import '../../control/button/button.dart';
import '../dialog/dialog.dart';
import '../drawer/drawer.dart';
import '../../../shared/icons/radix_icons.dart';
import '../../../shared/primitives/basic.dart';
import '../../../shared/primitives/outlined_container.dart';
import '../../../shared/primitives/overlay.dart';
import '../../../shared/primitives/subfocus.dart';
import '../../../shared/theme/theme.dart';
import '../../../shared/utils/constants.dart';
import '../../../shared/utils/geometry_extensions.dart';
import '../../../shared/utils/keyboard_shortcut_utils.dart';
import '../../../shared/utils/style_value.dart';
import '../../../shared/utils/util.dart';

part '_impl/styles/menu_text_styles.dart';
part '_impl/themes/base/menu_theme.dart';
part '_impl/core/menu_shortcut.dart';
part '_impl/core/menu_item.dart';
part '_impl/core/menu_radio_group.dart';
part '_impl/core/menu_radio.dart';
part '_impl/core/menu_divider.dart';
part '_impl/core/menu_gap.dart';
part '_impl/core/menu_button.dart';
part '_impl/core/menu_label.dart';
part '_impl/core/menu_checkbox.dart';
part '_impl/state/menu_button_state.dart';
part '_impl/core/menu_group_data.dart';
part '_impl/core/menu_data.dart';
part '_impl/core/menu_group.dart';
part '_impl/state/menu_group_state.dart';
part '_impl/core/menubar.dart';
part '_impl/utils/menu_intents.dart';
part '_impl/utils/menu_overlay_handler.dart';
part '_impl/utils/menu_directional_intent.dart';
part '_impl/themes/variants/menu_popup_theme.dart';
part '_impl/core/menu_popup.dart';
part '_impl/state/menubar_state.dart';
part '_impl/themes/variants/menubar_theme.dart';
part '_impl/utils/next_menu_focus_intent.dart';
part '_impl/utils/open_sub_menu_intent.dart';
