// GENERATED by tool/registry/gen_blocks_test.dart.
//
// P6-B1 block contract: every block must pump at 375, 768 and 1440 wide,
// under the neutral and claude presets in light and dark, with no exception
// and no overflow. A block's public widget is the preview, so it is pumped
// exactly as an app would render it.
//
// Regenerate with:
//   dart run tool/registry/gen_blocks_test.dart [--check]

import 'package:flutter_test/flutter_test.dart';

import 'blocks_support.dart';

import 'package:flutter_shadcn_kit/registry/blocks/account-01/account_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/account-02/account_02.dart';
import 'package:flutter_shadcn_kit/registry/blocks/calendar-01/calendar_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/calendar-02/calendar_02.dart';
import 'package:flutter_shadcn_kit/registry/blocks/dashboard-01/dashboard_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/dashboard-02/dashboard_02.dart';
import 'package:flutter_shadcn_kit/registry/blocks/login-01/login_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/login-02/login_02.dart';
import 'package:flutter_shadcn_kit/registry/blocks/login-03/login_03.dart';
import 'package:flutter_shadcn_kit/registry/blocks/otp-01/otp_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/pricing-01/pricing_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/sidebar-01/sidebar_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/sidebar-02/sidebar_02.dart';
import 'package:flutter_shadcn_kit/registry/blocks/sidebar-03/sidebar_03.dart';
import 'package:flutter_shadcn_kit/registry/blocks/signup-01/signup_01.dart';
import 'package:flutter_shadcn_kit/registry/blocks/signup-02/signup_02.dart';

void main() {
  for (final preset in blockPresets) {
    for (final brightness in blockBrightnesses) {
      testWidgets('$preset / ${brightness.name}', (WidgetTester tester) async {
        final theme = blockTheme(preset, brightness);
        for (final width in blockWidths) {
          await pumpBlock(tester, const Account01(), theme, width);
          await pumpBlock(tester, const Account02(), theme, width);
          await pumpBlock(tester, const Calendar01(), theme, width);
          await pumpBlock(tester, const Calendar02(), theme, width);
          await pumpBlock(tester, const Dashboard01(), theme, width);
          await pumpBlock(tester, const Dashboard02(), theme, width);
          await pumpBlock(tester, const Login01(), theme, width);
          await pumpBlock(tester, const Login02(), theme, width);
          await pumpBlock(tester, const Login03(), theme, width);
          await pumpBlock(tester, const Otp01(), theme, width);
          await pumpBlock(tester, const Pricing01(), theme, width);
          await pumpBlock(tester, const Sidebar01(), theme, width);
          await pumpBlock(tester, const Sidebar02(), theme, width);
          await pumpBlock(tester, const Sidebar03(), theme, width);
          await pumpBlock(tester, const Signup01(), theme, width);
          await pumpBlock(tester, const Signup02(), theme, width);
        }
      });
    }
  }
}
