// GENERATED by tool/registry/gen_blocks_test.dart.
//
// P6-B1 block metadata contract: every block directory has a `meta.json`
// whose category, viewport and files are all present, and whose declared deps
// are exactly the layer units the block imports. The dependency lists below
// are the ones the generator derived from the block's real imports with
// package:analyzer, so a drift between meta.json and the code changes this
// file and fails `gen_blocks_test.dart --check`.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../../tool/registry/src/categories.dart';

void main() {
  final appRoot = Directory.current.path;
  final ids = <String>[
    'account-01',
    'account-02',
    'calendar-01',
    'calendar-02',
    'dashboard-01',
    'dashboard-02',
    'login-01',
    'login-02',
    'login-03',
    'otp-01',
    'pricing-01',
    'sidebar-01',
    'sidebar-02',
    'sidebar-03',
    'signup-01',
    'signup-02',
  ];
  final derivedDeps = <String, Map<String, List<String>>>{
    'account-01': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'alert',
        'avatar',
        'button',
        'card',
        'divider',
        'input',
        'tabs',
        'text_area',
      ],
    },
    'account-02': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'breadcrumb',
        'button',
        'card',
        'checkbox',
        'divider',
        'switch',
      ],
    },
    'calendar-01': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>['date_math'],
      'components': <String>['button', 'calendar', 'card', 'divider'],
    },
    'calendar-02': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>['date_math'],
      'components': <String>['button', 'calendar', 'card', 'divider'],
    },
    'dashboard-01': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'avatar',
        'button',
        'card',
        'divider',
        'input',
        'table',
      ],
    },
    'dashboard-02': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'button',
        'card',
        'divider',
        'input',
        'progress',
        'tabs',
      ],
    },
    'login-01': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'card', 'checkbox', 'divider', 'input'],
    },
    'login-02': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'image', 'input'],
    },
    'login-03': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'card', 'divider', 'input'],
    },
    'otp-01': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'card', 'divider', 'input_otp'],
    },
    'pricing-01': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['badge', 'button', 'card', 'divider', 'input_otp'],
    },
    'sidebar-01': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'card', 'divider'],
    },
    'sidebar-02': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'avatar',
        'badge',
        'button',
        'card',
        'divider',
        'input',
        'progress',
      ],
    },
    'sidebar-03': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'avatar',
        'badge',
        'breadcrumb',
        'button',
        'card',
        'divider',
        'input',
        'progress',
      ],
    },
    'signup-01': <String, List<String>>{
      'foundation': <String>['gap'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>['button', 'card', 'checkbox', 'input'],
    },
    'signup-02': <String, List<String>>{
      'foundation': <String>['gap', 'icons'],
      'theme': <String>['theme'],
      'primitives': <String>[],
      'components': <String>[
        'button',
        'card',
        'checkbox',
        'divider',
        'input',
        'progress',
      ],
    },
  };

  test('every block directory is in the table', () {
    final onDisk =
        Directory('$appRoot/lib/registry/blocks')
            .listSync()
            .whereType<Directory>()
            .map((entity) => entity.path.split('/').last)
            .toList()
          ..sort();
    expect(onDisk, ids);
  });

  for (final id in ids) {
    group(id, () {
      final meta =
          jsonDecode(
                File(
                  '$appRoot/lib/registry/blocks/$id/meta.json',
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;

      test('meta carries the identity fields', () {
        expect(meta['id'], id);
        expect(meta['name'], isA<String>());
        expect(meta['name'], isNotEmpty);
        expect(meta['description'], isA<String>());
        expect(meta['description'], isNotEmpty);
        expect(meta['install'], 'flutter_shadcn add $id');
        expect(meta['import'], contains('/ui/shadcn/blocks/$id/'));
      });

      test('category comes from the block taxonomy', () {
        expect(
          meta['category'],
          isIn(blockCategories),
          reason: 'unknown block category',
        );
      });

      test('viewport is a known hint', () {
        expect(meta['viewport'], anyOf('desktop', 'mobile'));
      });

      test('deps use exactly the four layers', () {
        final deps = meta['deps'] as Map<String, dynamic>;
        expect(deps.keys.toSet(), <String>{
          'foundation',
          'theme',
          'primitives',
          'components',
        });
        for (final entry in deps.entries) {
          expect(entry.value, isA<List<dynamic>>(), reason: entry.key);
          for (final item in entry.value as List) {
            expect(item, isA<String>());
          }
        }
      });

      test('every listed file exists', () {
        for (final file in meta['files'] as List) {
          expect(
            File('$appRoot/lib/registry/blocks/$id/$file').existsSync(),
            isTrue,
            reason: '$id lists a missing $file',
          );
        }
      });

      test('README.md exists', () {
        expect(
          File('$appRoot/lib/registry/blocks/$id/README.md').existsSync(),
          isTrue,
        );
      });

      test('the entry file is the widget the generator found', () {
        final stem = id.replaceAll('-', '_');
        expect(
          File('$appRoot/lib/registry/blocks/$id/$stem.dart').existsSync(),
          isTrue,
        );
        expect(meta['import'], contains('$stem.dart'));
      });

      test('meta.json deps equal the real imports', () {
        final deps = meta['deps'] as Map<String, dynamic>;
        for (final layer in const <String>[
          'foundation',
          'theme',
          'primitives',
          'components',
        ]) {
          expect(
            deps[layer],
            derivedDeps[id]![layer],
            reason: 'meta.json deps.$layer',
          );
        }
      });
    });
  }

  test('every block is in the generated manifest', () {
    final manifest =
        jsonDecode(
              File(
                '$appRoot/lib/registry/manifests/registry.json',
              ).readAsStringSync(),
            )
            as Map<String, dynamic>;
    final blocks = manifest['blocks'] as Map<String, dynamic>;
    for (final id in ids) {
      expect(blocks.containsKey(id), isTrue, reason: '$id is missing');
    }
  });

  test('the manifest install root carries a blocks directory', () {
    final manifest =
        jsonDecode(
              File(
                '$appRoot/lib/registry/manifests/registry.json',
              ).readAsStringSync(),
            )
            as Map<String, dynamic>;
    final install = manifest['install'] as Map<String, dynamic>;
    expect(install['blocksDir'], 'blocks');
  });
}
