// Renders a [ThemeDocument] as the exact `app_theme.dart` that
// `flutter_shadcn theme apply <preset>` writes into an installed project.
//
// The rendering rules are the kit generator's
// (`flutter_shadcn_kit/tool/rearch/gen_app_theme.dart`, VM-safe, values-only):
// one const colour map per brightness, one `final` token block per brightness
// (`ShadowScale.derive` is a factory, so the blocks cannot be const), an
// optional const font block, one `build<Id>Theme(Brightness)` factory, and the
// tall-style `dart format` line-breaking (one line when the whole statement
// fits in 80 columns, otherwise one argument per line with a trailing comma).
//
// The generator itself imports `dart:io` and lives in the kit package, so it
// cannot run inside the web bundle; this port reproduces it exactly and
// `test/theme_dart_source_test.dart` asserts byte equality against the
// generated per-preset `dart` sources (which ARE the generator's output) for
// all 43 presets. That test is the guard against drift.

import 'package:flutter/widgets.dart';

import 'theme_document.dart';

/// The import line the CLI's generator uses inside an installed project.
const String kCliThemeImport = 'theme.dart';

/// The header every generated `app_theme.dart` starts with, with `@id`
/// replaced by [id].
String appThemeHeader(String id) =>
    '// Generated by flutter_shadcn — regenerate with: '
    'flutter_shadcn theme apply $id --refresh';

/// Renders [document] as `app_theme.dart`.
String themeDartSource(ThemeDocument document, {String? themeImport}) {
  final String import = themeImport ?? kCliThemeImport;
  final String prefix = camelCaseId(document.id);
  final String classPrefix = prefix.isEmpty
      ? prefix
      : prefix[0].toUpperCase() + prefix.substring(1);
  final StringBuffer out = StringBuffer()
    ..writeln(appThemeHeader(document.id))
    ..writeln();
  final List<List<String>> groups = <List<String>>[
    <String>['package:flutter/widgets.dart'],
    <String>[
      import,
      siblingUri(import, 'color_tokens.dart'),
      siblingUri(import, 'tokens.dart'),
    ],
  ];
  for (int i = 0; i < groups.length; i += 1) {
    if (i > 0) {
      out.writeln();
    }
    for (final String library in groups[i]) {
      out.writeln("import '$library';");
    }
  }
  for (final String source in <String>[
    _colorsSource(document, prefix, 'light'),
    _colorsSource(document, prefix, 'dark'),
    _tokensSource(document, prefix, 'Light'),
    _tokensSource(document, prefix, 'Dark'),
    if (document.hasFonts) _fontsSource(document, prefix),
    _buildSource(document, prefix, classPrefix),
  ]) {
    out
      ..writeln()
      ..writeln(source);
  }
  return out.toString();
}

String _colorsSource(ThemeDocument d, String prefix, String mode) {
  final bool dark = mode == 'dark';
  final Map<String, String> map = dark ? d.dark : d.light;
  final List<String> args = <String>[
    'brightness: Brightness.${dark ? 'dark' : 'light'}',
    for (final String key in kDocsColorTokenKeys)
      '$key: Color(0x${_argb(parseDocsHexColor(map[key]!))})',
  ];
  final String head =
      'const ShadcnColors $prefix${_capital(mode)}Colors = ShadcnColors';
  return '/// Colour tokens for the ${d.name} preset, $mode brightness.\n'
      '${_call(head, args, suffix: ';')}';
}

String _tokensSource(ThemeDocument d, String prefix, String mode) {
  final DocsShadowAtoms atoms = d.shadowOf(
    mode == 'Dark' ? Brightness.dark : Brightness.light,
  );
  final List<String> args = <String>[
    'radius: ${_num(d.radius)}',
    'spacingBase: ${_num(d.spacing * 16)}',
    for (final String step in kDocsTrackingSteps)
      if (d.tracking.containsKey(step))
        'tracking${_capital(step)}: ${_num(d.tracking[step]! * 16)}',
    _call(
      'shadows: ShadowScale.derive',
      <String>[
        'color: Color(0x${_argb(atoms.color)})',
        'opacity: ${_num(atoms.opacity)}',
        'blur: ${_num(atoms.blur)}',
        'spread: ${_num(atoms.spread)}',
        'offsetX: ${_num(atoms.offsetX)}',
        'offsetY: ${_num(atoms.offsetY)}',
      ],
      indent: '  ',
      appended: 1,
    ),
  ];
  final String head =
      'final ShadcnTokens $prefix$mode'
      'Tokens = ShadcnTokens';
  return '/// Non-colour tokens for the ${d.name} preset, '
      '${mode.toLowerCase()} brightness.\n${_call(head, args, suffix: ';')}';
}

String _fontsSource(ThemeDocument d, String prefix) {
  final List<String> args = <String>[
    for (final String slot in kDocsFontSlots)
      if (d.fonts.containsKey(slot))
        'font${_capital(slot)}: ${_quote(d.fonts[slot]!)}',
  ];
  return '/// Mode-independent font families for the ${d.name} preset.\n'
      "${_call('const ShadcnFonts ${prefix}Fonts = ShadcnFonts', args, suffix: ';')}";
}

String _buildSource(ThemeDocument d, String prefix, String classPrefix) {
  final List<String> args = <String>[
    'colors: isDark ? ${prefix}DarkColors : ${prefix}LightColors',
    'tokens: isDark ? ${prefix}DarkTokens : ${prefix}LightTokens',
    if (d.hasFonts) 'fonts: ${prefix}Fonts',
  ];
  return '/// Builds the ambient theme for the ${d.name} preset.\n'
      'ShadcnThemeData build${classPrefix}Theme(Brightness brightness) {\n'
      '  final isDark = brightness == Brightness.dark;\n'
      '  ${_call('return ShadcnThemeData', args, indent: '  ', suffix: ';')}\n'
      '}';
}

/// `amber-minimal` -> `amberMinimal`; strips anything that cannot appear in a
/// Dart identifier so the emitted names always compile.
String camelCaseId(String id) {
  final List<String> parts = id
      .split(RegExp('[^A-Za-z0-9]'))
      .where((String part) => part.isNotEmpty)
      .toList();
  final StringBuffer buffer = StringBuffer();
  for (final String part in parts) {
    buffer.write(buffer.isEmpty ? part.toLowerCase() : _capital(part));
  }
  return buffer.toString();
}

/// Sibling library of [uri]: same directory, [name] file name.
String siblingUri(String uri, String name) {
  final int cut = uri.lastIndexOf('/');
  return cut < 0 ? name : '${uri.substring(0, cut + 1)}$name';
}

/// Renders `head(a: 1, b: 2)` plus [suffix] on one line when the whole
/// statement fits in 80 columns, otherwise one argument per line with a
/// trailing comma and the closing parenthesis back at [indent]. [appended] is
/// the number of characters the caller puts after this call (the `,` of the
/// enclosing argument list); it counts towards the one-line fit but is not
/// emitted, so an exploded nested call still ends with a single comma.
String _call(
  String head,
  List<String> args, {
  String indent = '',
  String suffix = '',
  int appended = 0,
}) {
  final String flat = '$head(${args.join(', ')})$suffix';
  if (indent.length + flat.length + appended <= 80) {
    return flat;
  }
  final String body = args.map((String a) => '$indent  $a').join(',\n');
  return '$head(\n$body,\n$indent)$suffix';
}

/// `0xFFAABBCC`, always eight upper case digits.
String _argb(int argb) => argb.toRadixString(16).padLeft(8, '0').toUpperCase();

/// Shortest round-tripping Dart literal for [value] (`-30.0`, `3.84`, `0.0`).
String _num(double value) => value.toString();

/// Upper-cases the first character of [text].
String _capital(String text) =>
    text.isEmpty ? text : text[0].toUpperCase() + text.substring(1);

/// Single-quoted Dart string literal; escapes `\` and `'`.
String _quote(String value) =>
    "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
