// Copy payloads of the themes customizer (spec §2.7; D4 QA follow-up 2):
//
//  * Copy JSON — the selected preset's canonical JSON with the radius slider
//    value applied. Radius is the only customizer edit a preset document can
//    carry (the mode toggle changes which preview is shown, both mode blocks
//    always stay in the document).
//  * Copy Dart — the byte-exact `app_theme.dart` that
//    `flutter_shadcn theme apply <id>` writes into an installed project
//    (generated by the kit generator; see docs_preset_sources.dart).
//  * Get Code — the command that regenerates that file in a project.

import 'dart:convert';

import '../generated/docs_preset_sources.dart';

/// The command `Get Code` copies (`flutter_shadcn theme apply <id>`).
String themeApplyCommand(String presetId) =>
    'flutter_shadcn theme apply $presetId';

/// The canonical preset JSON with [radiusPx] applied.
///
/// The registry stores `radius` in rem; the rail's slider is in px, so the
/// value written back is `px / 16` (the same conversion the generated Dart
/// uses). Unknown ids return an empty string; the rail only ever passes ids
/// from [kPresetSources].
String presetJsonSource(String presetId, {required double radiusPx}) {
  final DocsPresetSource? source = kPresetSources[presetId];
  if (source == null) {
    return '';
  }
  final Object? decoded = jsonDecode(source.json);
  if (decoded is! Map<String, dynamic>) {
    return source.json;
  }
  decoded['radius'] = radiusPx / 16;
  return const JsonEncoder.withIndent('  ').convert(decoded);
}

/// The exact `app_theme.dart` the CLI generates for [presetId].
String presetDartSource(String presetId) =>
    kPresetSources[presetId]?.dart ?? '';
