name: flutter_cli_verification_example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  data_widget: ^0.0.2
  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/bootstrap.otf
    - assets/fonts/geist/Geist-Black.otf
    - assets/fonts/geist/Geist-BlackItalic.otf
    - assets/fonts/geist/Geist-Bold.otf
    - assets/fonts/geist/Geist-BoldItalic.otf
    - assets/fonts/geist/Geist-ExtraLightItalic.otf
    - assets/fonts/geist/Geist-Light.otf
    - assets/fonts/geist/Geist-LightItalic.otf
    - assets/fonts/geist/Geist-Medium.otf
    - assets/fonts/geist/Geist-MediumItalic.otf
    - assets/fonts/geist/Geist-Regular.otf
    - assets/fonts/geist/Geist-RegularItalic.otf
    - assets/fonts/geist/Geist-SemiBold.otf
    - assets/fonts/geist/Geist-SemiBoldItalic.otf
    - assets/fonts/geist/Geist-Thin.otf
    - assets/fonts/geist/Geist-ThinItalic.otf
    - assets/fonts/geist/Geist-UltraBlack.otf
    - assets/fonts/geist/Geist-UltraLight.otf
    - assets/fonts/geist/GeistMono-Black.otf
    - assets/fonts/geist/GeistMono-BlackItalic.otf
    - assets/fonts/geist/GeistMono-Bold.otf
    - assets/fonts/geist/GeistMono-BoldItalic.otf
    - assets/fonts/geist/GeistMono-ExtraLightItalic.otf
    - assets/fonts/geist/GeistMono-Italic.otf
    - assets/fonts/geist/GeistMono-Light.otf
    - assets/fonts/geist/GeistMono-LightItalic.otf
    - assets/fonts/geist/GeistMono-Medium.otf
    - assets/fonts/geist/GeistMono-MediumItalic.otf
    - assets/fonts/geist/GeistMono-Regular.otf
    - assets/fonts/geist/GeistMono-SemiBold.otf
    - assets/fonts/geist/GeistMono-SemiBoldItalic.otf
    - assets/fonts/geist/GeistMono-Thin.otf
    - assets/fonts/geist/GeistMono-ThinItalic.otf
    - assets/fonts/geist/GeistMono-UltraBlack.otf
    - assets/fonts/geist/GeistMono-UltraLight.otf
    - assets/fonts/lucide.ttf
    - assets/fonts/radix.otf
